version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - TZ=Asia/Jakarta
      - GENERIC_TIMEZONE=Asia/Jakarta
      - N8N_SECURE_COOKIE=false

      # Wajib agar semua data disimpan lokal (bukan default DB SQLite temp)
      - DB_TYPE=sqlite
      - DB_SQLITE_LOCATION=/home/node/.n8n/database.sqlite

      # Lokasi penyimpanan kredensial (optional tapi aman)
      - N8N_USER_FOLDER=/home/node/.n8n
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
